### ISSUE TITLE
Connection parameters from environment variables

### ISSUE THREAD

**Issue by jonbiemond** [tconbeer/harlequin-postgres#15]
Reading the connection parameters from environment variables would save some typing and make connecting to a Postgres database as easy as:
```bash
harlequin -a postgres
```

I propose the standard environment variables supported by Postgres and tools like `psql`: https://www.postgresql.org/docs/current/libpq-envars.html

**Comment by tconbeer** [comment]
I realize this isn't documented, but I think it might work already? We're just passing those options through to psycopg2, which I think will already read env vars for params not passed through to the connect method. You might need an empty connection string?

```
harlequin -a postgres ""
```

**Comment by jonbiemond** [comment]
Yep, you're right! It totally works! I didn't have to pass the empty connection string either.
