### ISSUE TITLE
Run init scripts at start-up (`.psqlrc`)

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/harlequin-postgres#17]
From https://github.com/tconbeer/harlequin/discussions/472

similar to duckdb implementation; see here for psql search paths:

https://pgpedia.info/p/psqlrc.html#:~:text=file%20for%20psql%20.-,Location,%25APPDATA%25%5Cpostgresql%5Cpsqlrc.

**Comment by tconbeer** [comment]
These scripts actually don't seem like they do much in the database, they all seem to just be focused on the psql client config.

**Comment by mahiki** [comment]
Here is what would go in my init script for trino or databricks:

```sql
use catalog my_team_default_catalog;
﻿﻿set time zone 'America/Los_Angeles';
```

I'm tired of typing this in for every session, but cant figure out how to set this on connection.
